# Generated by Django 4.2.4 on 2023-09-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Labourdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=255)),
                ('employee_id', models.CharField(max_length=255)),
                ('employee_age', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('task', models.CharField(max_length=255)),
                ('due_date', models.CharField(max_length=255)),
                ('start_time', models.CharField(max_length=255)),
                ('end_time', models.CharField(max_length=255)),
            ],
        ),
    ]
